### ISSUE TITLE
我在训练自己的数据集时出现了报错

### ISSUE THREAD

**Issue by xiaomazhi** [open-mmlab/mmsegmentation#2905]
Thanks for your error report and we appreciate it a lot.

**Checklist**

1. I have searched related issues but cannot get the expected help.
2. The bug has not been fixed in the latest version.

**Describe the bug**
运行train.py后报错
AttributeError: 'NoneType' object has no attribute 'get'

**Reproduction**

1. What command or script did you run?
python tools/train.py F:\PycharmProjects\mmsegmentation\my_models\deeplabv3plus\deeplabv3plus_r101-d8_512x512_20k_my_dataset.py

   ```none
   A placeholder for the command.
   ```

2. Did you make any modifications on the code or config? Did you understand what you have modified?
no
5. What dataset did you use?
mydataset

**Environment**

1. Please run `python mmseg/utils/collect_env.py` to collect necessary environment information and paste it here.
sys.platform: win32
Python: 3.9.16 (main, Mar  8 2023, 10:39:24) [MSC v.1916 64 bit (AMD64)]
CUDA available: True
numpy_random_seed: 2147483648
GPU 0: NVIDIA GeForce RTX 3060 Laptop GPU
CUDA_HOME: C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v12.1
NVCC: Cuda compilation tools, release 12.1, V12.1.66
GCC: n/a
PyTorch: 1.12.1+cu113
PyTorch compiling details: PyTorch built with:
  - C++ Version: 199711
  - MSVC 192829337
  - Intel(R) Math Kernel Library Version 2020.0.2 Product Build 20200624 for Intel(R) 64 architecture applications
  - Intel(R) MKL-DNN v2.6.0 (Git Hash 52b5f107dd9cf10910aaa19cb47f3abf9b349815)
  - OpenMP 2019
  - LAPACK is enabled (usually provided by MKL)
  - CPU capability usage: AVX2
  - CUDA Runtime 11.3
  - NVCC architecture flags: -gencode;arch=compute_37,code=sm_37;-gencode;arch=compute_50,code=sm_50;-gencode;arch=compute_60,code=sm_60;-gencode;arch=compute_61,code=sm_61;-gencode;arch=compute_70,code=sm_70;-gencode;arch=compute_75,code=sm_75;-gencode;arch=compute_80,code=sm_80;-gencode;arch=compute_86,code=sm_86;-gencode;arch=compute_37,code=compute_37
  - CuDNN 8.3.2  (built against CUDA 11.5)
  - Magma 2.5.4
  - Build settings: BLAS_INFO=mkl, BUILD_TYPE=Release, CUDA_VERSION=11.3, CUDNN_VERSION=8.3.2, CXX_COMPILER=C:/actions-runner/_work/pytorch/pytorch/builder/windows/tmp_bin/sccache-cl.exe, CXX_FLAGS=/DWIN32 /D_WINDOWS /GR /EHsc /w /b
igobj -DUSE_PTHREADPOOL -openmp:experimental -IC:/actions-runner/_work/pytorch/pytorch/builder/windows/mkl/include -DNDEBUG -DUSE_KINETO -DLIBKINETO_NOCUPTI -DUSE_FBGEMM -DUSE_XNNPACK -DSYMBOLICATE_MOBILE_DEBUG_HANDLE -DEDGE_PROFILE
R_USE_KINETO, LAPACK_INFO=mkl, PERF_WITH_AVX=1, PERF_WITH_AVX2=1, PERF_WITH_AVX512=1, TORCH_VERSION=1.12.1, USE_CUDA=ON, USE_CUDNN=ON, USE_EXCEPTION_PTR=1, USE_GFLAGS=OFF, USE_GLOG=OFF, USE_MKL=ON, USE_MKLDNN=OFF, USE_MPI=OFF, USE_NCCL=OFF, USE_NNPACK=OFF, USE_OPENMP=ON, USE_ROCM=OFF,

TorchVision: 0.13.1+cpu
OpenCV: 4.7.0
MMEngine: 0.7.2
MMSegmentation: 1.0.0+b600f7c

3. You may add addition that may be helpful for locating the problem, such as
   - How you installed PyTorch \[e.g., pip, conda, source\]
   - Other environment variables that may be related (such as `$PATH`, `$LD_LIBRARY_PATH`, `$PYTHONPATH`, etc.)

**Error traceback**

(pt3.9) F:\PycharmProjects\mmsegmentation>python tools/train.py F:\PycharmProjects\mmsegmentation\my_models\deeplabv3plus\deeplabv3plus_r101-d8_512x512_20k_my_dataset.py 
Traceback (most recent call last):
  File "F:\PycharmProjects\mmsegmentation\tools\train.py", line 104, in <module>
    main()
  File "F:\PycharmProjects\mmsegmentation\tools\train.py", line 93, in main
    runner = Runner.from_cfg(cfg)
  File "F:\Anaconda\envs\pt3.9\lib\site-packages\mmengine\runner\runner.py", line 439, in from_cfg
    runner = cls(
  File "F:\Anaconda\envs\pt3.9\lib\site-packages\mmengine\runner\runner.py", line 353, in __init__
    self.setup_env(env_cfg)
  File "F:\Anaconda\envs\pt3.9\lib\site-packages\mmengine\runner\runner.py", line 643, in setup_env
    if env_cfg.get('cudnn_benchmark'):
AttributeError: 'NoneType' object has no attribute 'get'

```none
A placeholder for trackback.
```

**Bug fix**

If you have already identified the reason, you can provide the information here. If you are willing to create a PR to fix it, please also leave a comment here and that would be much appreciated!

**Comment by sammilei** [comment]
Got the same error when training with custom data using segmenter. The same config was working with mmcv=1.6.0
