### ISSUE TITLE
K-Net ADE20K is something error!

### ISSUE THREAD

**Issue by Leeinsn** [open-mmlab/mmsegmentation#2105]
When I train with config knet_s3_upernet_r50-d8_8x2_512x512_adamw_80k_ade20k.py, it show that 'AttributeError: EncoderDecoder: 'IterativeDecodeHead' object has no attribute 'out_channels''

**Comment by mangelroman** [comment]
I get the exact same error running inference with knet_s3_upernet_swin-l_8x2_640x640_adamw_80k_ade20k

**Comment by MengzhangLI** [comment]
Hi, guys. @Leeinsn @mangelroman 

https://github.com/open-mmlab/mmsegmentation/blob/master/mmseg/models/decode_heads/knet_head.py#L414

Could you fix `super(BaseDecodeHead, self).__init__(**kwargs)` to `super(IterativeDecodeHead, self).__init__(**kwargs)` and try again? Looking forward to your reply.

**Comment by mangelroman** [comment]
> 
I tested again with the proposed changes and got a different error. This is what I did:
- modified the requested file
- run `pip install -v -e .` in the mmsegmentation cloned repository 
- download the model weights again via mim download

Please find below the full error trace after executing `init_segmentor()`

```
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
File ~/miniconda3/envs/archy/lib/python3.9/site-packages/mmcv/utils/registry.py:69, in build_from_cfg(cfg, registry, default_args)
     68 try:
---> 69     return obj_cls(**args)
     70 except Exception as e:
     71     # Normal TypeError does not print class name.

File ~/repos/mmsegmentation/mmseg/models/decode_heads/knet_head.py:414, in IterativeDecodeHead.__init__(self, num_stages, kernel_generate_head, kernel_update_head, **kwargs)
    412 def __init__(self, num_stages, kernel_generate_head, kernel_update_head,
    413              **kwargs):
--> 414     super(IterativeDecodeHead, self).__init__(**kwargs)
    415     #super(BaseDecodeHead, self).__init__(**kwargs)

TypeError: __init__() missing 2 required positional arguments: 'in_channels' and 'channels'

During handling of the above exception, another exception occurred:

TypeError                                 Traceback (most recent call last)
File ~/miniconda3/envs/archy/lib/python3.9/site-packages/mmcv/utils/registry.py:69, in build_from_cfg(cfg, registry, default_args)
     68 try:
---> 69     return obj_cls(**args)
     70 except Exception as e:
     71     # Normal TypeError does not print class name.
...
     70 except Exception as e:
     71     # Normal TypeError does not print class name.
---> 72     raise type(e)(f'{obj_cls.__name__}: {e}')

TypeError: EncoderDecoder: IterativeDecodeHead: __init__() missing 2 required positional arguments: 'in_channels' and 'channels'
```

**Comment by lojzezust** [comment]
Hi! I've had the same error. The issue seems to be caused by commit c1c942e8, which added the `out_channels` attribute to `BaseDecodeHead`. Since `IterativeDecodeHead` bypasses the `BaseDecodeHead` initialization, the attribute is not set and leads to errors.

A temporary fix for me was to use set `self.out_channels = self.num_classes` in the `__init__` method of `IterativeDecodeHead`.

However, a more general solution would probably be to fix the bypass as @MengzhangLI proposed and provide the required arguments.

**Comment by mangelroman** [comment]
> Hi! I've had the same error. The issue seems to be caused by commit [c1c942e](https://github.com/open-mmlab/mmsegmentation/commit/c1c942e8fc22dc73d6a378a811d6c4c0c2ed73e4), which added the `out_channels` attribute to `BaseDecodeHead`. Since `IterativeDecodeHead` bypasses the `BaseDecodeHead` initialization, the attribute is not set and leads to errors.
> 
> A temporary fix for me was to set `self.out_channels = self.num_classes` in the `__init__` method of `IterativeDecodeHead`.
> 
> However, a more general solution would probably be to fix the bypass as @MengzhangLI proposed and provide the required positional arguments.

This temporary fix works for me as well, many thanks.

**Comment by xbbkok** [comment]
I had the same error

**Comment by xiexinch** [comment]
We have fixed this problem. Might try the latest version.

https://github.com/open-mmlab/mmsegmentation/pull/2333

**Comment by xiexinch** [comment]
Closing the issue, as there is no activity for a while.
We hope your issue has been resolved. 
If not, please feel free to open a new one.
