### ISSUE TITLE
`mask2former` raised error: `class `Mask2FormerHead` in mmseg/models/decode_heads/mask2former_head.py: __init__() got an unexpected keyword argument 'in_channels'`

### ISSUE THREAD

**Issue by ff98li** [open-mmlab/mmsegmentation#2914]
Hi, I was running mask2former using the base config `mask2former_swin-b-in1k-384x384-pre_8xb2-160k_ade20k-640x640.py`, and it rasied the following error:
```
TypeError: class `EncoderDecoder` in mmseg/models/segmentors/encoder_decoder.py: class `Mask2FormerHead` in mmseg/models/decode_heads/mask2former_head.py: __init__() got an unexpected keyword argument 'in_channels'
```
I looked into `mask2former_head.py` and suspected the root of the problem may lie in these lines:
https://github.com/open-mmlab/mmsegmentation/blob/b600f7cb26829afa2c785af41755391626fbb446/mmseg/models/decode_heads/mask2former_head.py#L9-L13

As I hadn't installed `mmdetection`, the alternatively imported `BaseModule` used as `Mask2FormerHead` from `mmengine.model` may not recognise `in_channels`. However after I installed `mmdetection` via `mim install mmdet`, I was experiencing the issue decribed in [issue#2892](https://github.com/open-mmlab/mmsegmentation/issues/2892), as `mmengine` version was automatically updated to `0.7.2` from `0.7.0` with `mmdetection` installed. I tried downgrading `mmengine` back to `0.7.0` and installed `mmdetection` by directly cloning its repo and manually installing via `pip` as instructed  in [here](https://mmdetection.readthedocs.io/en/latest/get_started.html#installation), but the latest version of `mmdetection` is incompatible with `mmengine==0.7.0`.

**Environment**
```
sys.platform: linux
Python: 3.8.16 | packaged by conda-forge | (default, Feb  1 2023, 16:01:55) [GCC 11.3.0]
CUDA available: True
numpy_random_seed: 2147483648
GPU 0: NVIDIA RTX A6000
CUDA_HOME: /usr/local/cuda
NVCC: Cuda compilation tools, release 11.6, V11.6.124
GCC: gcc (Ubuntu 9.4.0-1ubuntu1~20.04.1) 9.4.0
PyTorch: 2.0.0
PyTorch compiling details: PyTorch built with:
  - GCC 9.3
  - C++ Version: 201703
  - Intel(R) oneAPI Math Kernel Library Version 2022.1-Product Build 20220311 for Intel(R) 64 architecture applications
  - Intel(R) MKL-DNN v2.7.3 (Git Hash 6dbeffbae1f23cbbeae17adb7b5b13f1f37c080e)
  - OpenMP 201511 (a.k.a. OpenMP 4.5)
  - LAPACK is enabled (usually provided by MKL)
  - NNPACK is enabled
  - CPU capability usage: AVX2
  - CUDA Runtime 11.7
  - NVCC architecture flags: -gencode;arch=compute_37,code=sm_37;-gencode;arch=compute_50,code=sm_50;-gencode;arch=compute_60,code=sm_60;-gencode;arch=compute_61,code=sm_61;-gencode;arch=compute_70,code=sm_70;-gencode;arch=compute_75,code=sm_75;-gencode;arch=compute_80,code=sm_80;-gencode;arch=compute_86,code=sm_86;-gencode;arch=compute_37,code=compute_37
  - CuDNN 8.5
  - Magma 2.6.1
  - Build settings: BLAS_INFO=mkl, BUILD_TYPE=Release, CUDA_VERSION=11.7, CUDNN_VERSION=8.5.0, CXX_COMPILER=/opt/rh/devtoolset-9/root/usr/bin/c++, CXX_FLAGS= -D_GLIBCXX_USE_CXX11_ABI=0 -fabi-version=11 -Wno-deprecated -fvisibility-inlines-hidden -DUSE_PTHREADPOOL -DNDEBUG -DUSE_KINETO -DLIBKINETO_NOROCTRACER -DUSE_FBGEMM -DUSE_QNNPACK -DUSE_PYTORCH_QNNPACK -DUSE_XNNPACK -DSYMBOLICATE_MOBILE_DEBUG_HANDLE -O2 -fPIC -Wall -Wextra -Werror=return-type -Werror=non-virtual-dtor -Werror=bool-operation -Wnarrowing -Wno-missing-field-initializers -Wno-type-limits -Wno-array-bounds -Wno-unknown-pragmas -Wunused-local-typedefs -Wno-unused-parameter -Wno-unused-function -Wno-unused-result -Wno-strict-overflow -Wno-strict-aliasing -Wno-error=deprecated-declarations -Wno-stringop-overflow -Wno-psabi -Wno-error=pedantic -Wno-error=redundant-decls -Wno-error=old-style-cast -fdiagnostics-color=always -faligned-new -Wno-unused-but-set-variable -Wno-maybe-uninitialized -fno-math-errno -fno-trapping-math -Werror=format -Werror=cast-function-type -Wno-stringop-overflow, LAPACK_INFO=mkl, PERF_WITH_AVX=1, PERF_WITH_AVX2=1, PERF_WITH_AVX512=1, TORCH_DISABLE_GPU_ASSERTS=ON, TORCH_VERSION=2.0.0, USE_CUDA=ON, USE_CUDNN=ON, USE_EXCEPTION_PTR=1, USE_GFLAGS=OFF, USE_GLOG=OFF, USE_MKL=ON, USE_MKLDNN=ON, USE_MPI=OFF, USE_NCCL=ON, USE_NNPACK=ON, USE_OPENMP=ON, USE_ROCM=OFF, 

TorchVision: 0.15.0
OpenCV: 4.7.0
MMEngine: 0.7.0
MMSegmentation: 1.0.0rc6+ff95416
```

Thank you in advance!

**Comment by LHamnett** [comment]
@ff98li , I am not sure if this will solve your issue, but check the documentation here:
https://github.com/open-mmlab/mmsegmentation/tree/b600f7cb26829afa2c785af41755391626fbb446/configs/mask2former

It is recommended to install mmdetection to run this model via:
 pip install "mmdet>=3.0.0rc4"

**Comment by ff98li** [comment]
> @ff98li , I am not sure if this will solve your issue, but check the documentation here: https://github.com/open-mmlab/mmsegmentation/tree/b600f7cb26829afa2c785af41755391626fbb446/configs/mask2former
> 
> It is recommended to install mmdetection to run this model via: pip install "mmdet>=3.0.0rc4"

Thank you for the reply @LHamnett! I indeed have tried installing mmdetection via `pip install "mmdet>=3.0.0rc4`, which raised the following error when running the model:
```
AssertionError: MMEngine==0.7.0 is used but incompatible. Please install mmengine>=0.7.1, <1.0.0.
```
while any `mmengine` version above 0.7.0 will raise the error in issue#2892. I have also tried "mmdet==3.0.0rc4" but it just brought me to [issue#2619](https://github.com/open-mmlab/mmsegmentation/issues/2619), and...since the current `dev-3.x` for mmdetection (which is the same as the `main` at this point) mentioned in the issue now requires `mmengine>=0.7.1`, it ultimately leads us back to issue#2892 again.

**Comment by sammilei** [comment]
Same issue here and haven't found a solution.

**Comment by claverru** [comment]
Same problem, when trying to use any mask2former model.

**Comment by RPetitpierre** [comment]
Same issue here as well.

**Comment by RPetitpierre** [comment]
Solved the problem by installing mmdetection without mmengine:
`git clone https://github.com/open-mmlab/mmdetection.git`
`cd mmdetection`
`pip install -v -e .`

**Comment by huanruizhang123** [comment]
> 通过在没有mmengine的情况下安装mmdetection 解决了这个问题： `git clone https://github.com/open-mmlab/mmdetection.git` `cd mmdetection` `pip install -v -e .`

May I ask how to install, so that MMdetct and MMseg will not coincide

**Comment by RPetitpierre** [comment]
Sorry for the confusion. So I had to install mmdetection, even though I was trying to perform semantic sementation with mmsegmentation. This is indicated in the Mask2Former README ([here](https://github.com/open-mmlab/mmsegmentation/blob/e64548fda0221ad708f5da29dc907e51a644c345/configs/mask2former/README.md)).
There are several ways to install mmdetection (cf. instructions [here](https://mmdetection.readthedocs.io/en/latest/get_started.html)). However, in my case, installing mmdetection via mim seems to cause this bug. Thus, I directly installed it from root. After this, everything seems to work fine.

**Comment by huanruizhang123** [comment]
> 所以我不得不安装mmdetection，即使我正尝试使用mmsegmentation执行语言义分割。Mask2Former自述文件（[此处](https://github.com/open-mmlab/mmsegmentation/blob/e64548fda0221ad708f5da29dc907e51a644c345/configs/mask2former/README.md)）中对这样进行了说明。 有几种安装mmdetection的方法（参见[此处的](https://mmdetection.readthedocs.io/en/latest/get_started.html)说明） 。但是，就我而言，通过 mim 安装 mmdetection 似乎会导致此错误。因此，我直接从 root 安装它。在此之后，一次切换似乎都正常。
I downloaded the MMdet compressed package, and put it in the same directory as MMseg. Both in the same conda environment, the following error will occur, class `Mask2FormerHead` in mmseg/models/decode_heads/mask2former_head.py: 'ConfigDict' object has no attribute 'transformerlayers'
![image](https://github.com/open-mmlab/mmsegmentation/assets/124413465/75f27f3a-01aa-42a6-b2c2-61b502ce195e)
![image](https://github.com/open-mmlab/mmsegmentation/assets/124413465/10c64f5e-fd67-4f39-8904-3cc16d1e839a)

**Comment by HePengguang** [comment]
same issue

**Comment by OSSome01** [comment]
> I used the following code to configure the environment in kaggle, but it still reports an same error during inference
> 
> ```python
> !pip install -U openmim
> !mim install "mmengine>=0.7.0"
> !pip install -q /kaggle/input/frozen-packages-mmdetection/mmcv-2.0.1-cp310-cp310-linux_x86_64.whl
> 
> !git clone https://github.com/open-mmlab/mmdetection.git
> %cd mmdetection
> !pip install -v -e .
> %cd ..
> 
> !rm -rf mmsegmentation
> !git clone https://github.com/open-mmlab/mmsegmentation.git
> %cd mmsegmentation
> !pip install -v -e .
> ```
> 
> inference:
> 
> ```python
> !wget https://download.openmmlab.com/mmsegmentation/v0.5/mask2former/mask2former_swin-l-in22k-384x384-pre_8xb2-90k_cityscapes-512x1024/mask2former_swin-l-in22k-384x384-pre_8xb2-90k_cityscapes-512x1024_20221202_141901-28ad20f1.pth -P checkpoint
> from mmseg.apis import inference_model
> from mmengine.model.utils import revert_sync_batchnorm
> from mmseg.apis import init_model
> 
> config_file = 'configs/mask2former/mask2former_swin-l-in22k-384x384-pre_8xb2-90k_cityscapes-512x1024.py'
> 
> checkpoint_file = 'checkpoint/mask2former_swin-l-in22k-384x384-pre_8xb2-90k_cityscapes-512x1024_20221202_141901-28ad20f1.pth'
> 
> model = init_model(config_file, checkpoint_file, device='cuda:0')
> 
> result = inference_model(model, img_path)
> pred_mask = result.pred_sem_seg.data[0].detach().cpu().numpy()
> 
> display.clear_output()
> img_bgr = cv2.imread(img_path)
> plt.figure(figsize=(14, 8))
> plt.imshow(img_bgr[:,:,::-1])
> plt.imshow(pred_mask, alpha=0.55)
> plt.axis('off')
> plt.savefig('outputs/B2-1.jpg')
> plt.show()
> ```
> 
> error message:
> 
> ```python
> TypeError: class `EncoderDecoder` in mmseg/models/segmentors/encoder_decoder.py: class `Mask2FormerHead` in mmseg/models/decode_heads/mask2former_head.py: __init__() got an unexpected keyword argument 'in_channels'
> ```

I get the same error as well. Has anyone solved this?

**Comment by ytzfhqs** [comment]
@OSSome01 @HePengguang After some experimentation I have solved the problem, as @edsml-hmc122  said, you must install mmdetection after mmsegmentation and you can't use the git clone method to install it, otherwise it reports an error. I have put my installation code below.
```python
from IPython import display
!pip install -U openmim

!rm -rf mmsegmentation
!git clone https://github.com/open-mmlab/mmsegmentation.git
%cd mmsegmentation
!pip install -e .

!pip install "mmdet>=3.0.0rc4"

!pip install -q /kaggle/input/frozen-packages-mmdetection/mmcv-2.0.1-cp310-cp310-linux_x86_64.whl
display.clear_output()
```
As of 14 July 2023, this method works in kaggle. I placed my kaggle notebook [here](https://www.kaggle.com/code/haoqingsong/mask2former-inference) which contains the environment installation and Mask2Former  Inference . But there is another problem is when I want to use CPU for inference, i.e. when I set the device parameter to 'cpu' I get an error: ``libc10_cuda.so: cannot open shared object file ``, I don't know how to solve it, I can only do inference in kaggle GPU100 environment, if there is a solution please let me know, thanks.

BTW, I haven't verified the validity of the above code on win and colab platforms, it might only work on kaggle platforms。

**Comment by OSSome01** [comment]
Thank you! This worked on my linux laptop (Pop_OS 22.04)

**Comment by xiexinch** [comment]
It requires installing mmdetection.
Might follow our document https://github.com/open-mmlab/mmsegmentation/tree/main/configs/mask2former#usage to use it.

**Comment by Fragmentszz** [comment]
just install ```mmdet``` :)

**Comment by ff98li** [comment]
Since solutions have been proposed above and mmseg version has gone through several iterations, I'm closing this nearly 2-year old issue.
